---
title: "Использование языка R для анализа ЭЭГ"
output:
  html_document: default
  html_notebook: default
  pdf_document: default
---

Подключение библиотек
---
```{r, comment='library', results='markup'}
library("edf")
library("xgboost")
library("signal")
```

Функция открытия файла формата edf
---
Открываем файлы из текущей директории
```{r, comment='openEeg', results='markup'}
openEeg <- function(shortfilename){
  datafile = paste(getwd(), shortfilename, sep = '/')
  eeg = read.edf(datafile)
  return(eeg)
}
```

Функция создания обучающей выборки из ЭЭГ
---

```{r, comment='StructEegData', results='markup'}

structEegData <- function(eeg){ 
  
  sampleRate = eeg$header.signal$EEG_Fp1$samplingrate;
  bt <- butter(4, W =  c(45/sampleRate*2, 55/sampleRate*2), type = 'stop')
  btlow <- butter(8, W = 30/sampleRate*2, type = 'low')
  
  for (j in 1:21)
  {
     eeg$signal[[j]]$data = filter(bt, eeg$signal[[j]]$data)
     eeg$signal[[j]]$data = filter(btlow, eeg$signal[[j]]$data)
  }
  
  numberOfStimuli = grep("\\([12]\\)", eeg$events$annotation) # Находим те события, которые отвечают за стимул
  stimuliCount = length(numberOfStimuli) 
  

  output = numeric(stimuliCount)
  
  ## Подготавливаю матрицу для фходных данных для обучения
  
  
 
  
  ## Анализ происходит по 0.5 сек
  samplesCount = round(sampleRate * 0.5)
  input = matrix(data = 0, nrow = 21, ncol = samplesCount*2)
  counter = 0;
  
  for (i in numberOfStimuli)
  {
    counter = counter +1;
    onSet = round((eeg$events$onset[i])*sampleRate)
    buffer = matrix(data = 0, nrow = 21, ncol = samplesCount);
    for (j in 1:21)
    {
      buffer[j,] = eeg$signal[[j]]$data[onSet:(onSet + samplesCount - 1)]
    }
    if(grepl("\\(1\\)", eeg$events$annotation[i]))
    {
      input[,1:samplesCount] = input[,1:samplesCount] + buffer;
    }
    else
    {
      input[,(samplesCount+1):(samplesCount*2)] = input[,(samplesCount+1):(samplesCount*2)] + buffer;
    }
    
   
    output[counter] = as.numeric(grepl("\\(1\\)", eeg$events$annotation[i]));
    
  }
  input[,1:samplesCount] = input[,1:samplesCount]/sum(output);
  input[,(samplesCount+1):(samplesCount*2)] = input[,(samplesCount+1):(samplesCount*2)]/sum(1-output); 
  data = list(x = input, y = output);
  return(data)
}
```

Открытие данных
---
Открывает данные исследования с помощью созданнх функций
```{r, comment='OpenData', results='markup'}
dataFrame1 <- structEegData(openEeg("Мухуров/170417_0014_EEG.edf"))
dataFrame2 <- structEegData(openEeg("Смирнов/24042017.edf"))
dataFrame3 <- structEegData(openEeg("Кайдак/170428_0019_EEG_redblue.edf"))
dataFrame3 <- structEegData(openEeg("Кайдак/170428_0019_EEG_redblue.edf"))
## d:\EEG\ColorRecognizer\Reeg\Тестовые по реальным фотостимуляциям\170428_000008_EEG.edf
```

Обучение (Бустинг)
---
Подготавливаем данные и делим их на тренировочные и тестовые данные
```{r}
input = rbind(dataFrame1$x, dataFrame2$x)
output = c(dataFrame1$y, dataFrame2$y)
frameCount = length(output)

trainIndex = runif(frameCount) > 0.1

inputTrain = input[trainIndex,]
inputTest = input[!trainIndex,]

outputTrain = output[trainIndex]
outputTest = output[!trainIndex]

dtrain = xgb.DMatrix(data = inputTrain, label = outputTrain)
dtest = xgb.DMatrix(data = inputTest, label = outputTest)
watchlist = list(train = dtrain, test = dtest)
```
Сам бустинг
```{r}

bst <- xgb.train(data = dtrain,  max.depth = 3, eps = 1, nthread = 2, nround = 3, objective = "binary:logistic", watchlist = watchlist)

```
```{r}
nChan = 18
plot((1:250)/500,dataFrame3$x[nChan,1:250], type = 'l', col = 'blue')
lines((1:250)/500,dataFrame3$x[nChan,251:500], type = 'l', col='red')
```


